"""initial

Revision ID: 85569b68d326
Revises: 
Create Date: 2026-07-01 09:52:16.784103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85569b68d326'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_sources',
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('authors', sa.JSON(), nullable=False),
    sa.Column('source_type', sa.Enum('pubmed', 'who', 'nice', 'cochrane', 'apa', 'nhs', 'other', name='source_type'), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('doi', sa.String(length=256), nullable=True),
    sa.Column('pubmed_id', sa.String(length=64), nullable=True),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('full_text_available', sa.Boolean(), nullable=False),
    sa.Column('qdrant_vector_id', sa.String(length=256), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('evidence_level', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('anonymous_id', sa.String(length=64), nullable=False),
    sa.Column('consent_given', sa.Boolean(), nullable=False),
    sa.Column('consent_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('preferred_language', sa.String(length=10), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_anonymous_id'), 'users', ['anonymous_id'], unique=True)
    op.create_table('conversation_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('active', 'ended', 'crisis_escalated', name='session_status'), nullable=False),
    sa.Column('primary_theme', sa.String(length=128), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('detected_emotions', sa.JSON(), nullable=False),
    sa.Column('detected_themes', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_sessions_user_id'), 'conversation_sessions', ['user_id'], unique=False)
    op.create_table('memory_snapshots',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_type', sa.Enum('session', 'cross_session', name='snapshot_type'), nullable=False),
    sa.Column('goals_summary', sa.Text(), nullable=True),
    sa.Column('stressors', sa.JSON(), nullable=False),
    sa.Column('strengths', sa.JSON(), nullable=False),
    sa.Column('recurring_themes', sa.JSON(), nullable=False),
    sa.Column('coping_strategies_tried', sa.JSON(), nullable=False),
    sa.Column('progress_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['conversation_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_snapshots_session_id'), 'memory_snapshots', ['session_id'], unique=False)
    op.create_index(op.f('ix_memory_snapshots_user_id'), 'memory_snapshots', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', 'system', name='message_role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('emotions', sa.JSON(), nullable=False),
    sa.Column('cognitive_distortions', sa.JSON(), nullable=False),
    sa.Column('themes', sa.JSON(), nullable=False),
    sa.Column('safety_flags', sa.JSON(), nullable=False),
    sa.Column('rag_sources', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['conversation_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_session_id'), 'messages', ['session_id'], unique=False)
    op.create_table('safety_events',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('suicidal_ideation', 'self_harm', 'abuse', 'psychosis', 'mania', 'general_crisis', name='safety_event_type'), nullable=False),
    sa.Column('severity', sa.Enum('low', 'moderate', 'high', 'critical', name='safety_severity'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('triggering_message_id', sa.UUID(), nullable=True),
    sa.Column('response_sent', sa.Text(), nullable=True),
    sa.Column('resources_provided', sa.JSON(), nullable=False),
    sa.Column('reviewed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['conversation_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_safety_events_session_id'), 'safety_events', ['session_id'], unique=False)
    op.create_index(op.f('ix_safety_events_user_id'), 'safety_events', ['user_id'], unique=False)
    op.create_table('user_goals',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('active', 'achieved', 'abandoned', name='goal_status'), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('source_message_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_goals_user_id'), 'user_goals', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_goals_user_id'), table_name='user_goals')
    op.drop_table('user_goals')
    op.drop_index(op.f('ix_safety_events_user_id'), table_name='safety_events')
    op.drop_index(op.f('ix_safety_events_session_id'), table_name='safety_events')
    op.drop_table('safety_events')
    op.drop_index(op.f('ix_messages_session_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_memory_snapshots_user_id'), table_name='memory_snapshots')
    op.drop_index(op.f('ix_memory_snapshots_session_id'), table_name='memory_snapshots')
    op.drop_table('memory_snapshots')
    op.drop_index(op.f('ix_conversation_sessions_user_id'), table_name='conversation_sessions')
    op.drop_table('conversation_sessions')
    op.drop_index(op.f('ix_users_anonymous_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('knowledge_sources')
    # ### end Alembic commands ###
